### ISSUE TITLE
Does your language has __asm__()?

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#122]
@travisdoor

**Comment by travisdoor** [comment]
no

**Comment by travisdoor** [comment]
I just quickly thought about this, and it would be quite hard to implement since one of the main concepts of this language is compile time execution. Basically everything in BL can be executed in compile time, custom MIR (Middle Intermediate Representation) language can be executed in VM during compilation, so also the asm block should have this functionality and I'm not sure about it's MIR representation.
What exactly do you want to achieve with this?
